db:
  enabled: true
  instances: 2
  storage:
    size: 10Gi
    storageClass: ai-ebs
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"


litellm:
  fullnameOverride: litellm
  replicaCount: 1
  
  db:
    useExisting: true
    deployStandalone: false
    endpoint: "litellm-pg-rw"
    database: app
    secret:
      name: litellm-pg-app
      usernameKey: username
      passwordKey: password
      
  envVars:
    {
      USE_DDTRACE: "false",
      LITELLM_MODE: "production",
    }
  
  # if set, use this secret for the master key; otherwise, autogenerate a new one
  masterkeySecretName: "litellm-master-key"
  
  # if set, use this secret key for the master key; otherwise, use the default key
  masterkeySecretKey: "master_key"
  
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - litellm
          topologyKey: "kubernetes.io/hostname"
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  
  environmentSecrets:
    - litellm-openai-api-key
    - litellm-gemini-api-key
    - litellm-fireworks-key
    - litellm-anthropic-api-key
    - litellm-redis-secret
  
  ingress:
    enabled: true
    hosts:
      - host: api.ai.kivoyo.com
        paths:
          - path: /
            pathType: Prefix
    className: alb
    annotations:
      alb.ingress.kubernetes.io/tags: Environment=dev,Owner=adorsys-gis
      alb.ingress.kubernetes.io/load-balancer-name: ai-adorsys-gis
      alb.ingress.kubernetes.io/listen-ports: |
        [
          {
            "HTTP":80
          },
          {
            "HTTPS": 443
          }
        ]
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:571075516563:certificate/980a6ebb-a87e-4cfb-b8bf-3d0e5da5acf5"
      external-dns.alpha.kubernetes.io/hostname: "api.ai.kivoyo.com"
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
      alb.ingress.kubernetes.io/healthy-threshold-count: "2"
      alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
  
  proxy_config:
    litellm_settings:
      cache: True
      cache_params: # set cache params for redis
        type: redis
        namespace: "litellm.caching.caching"
    model_list:
      # At least one model must exist for the proxy to start.
      - model_name: qwen3-coder-480b-a35b-instruct
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-coder-480b-a35b-instruct
        model_info:
          supports_function_calling: true
      - model_name: qwen3-235b-a22b
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b
          api_key: os.environ/FIREWORKS_AI_API_KEY
        model_info:
          supports_function_calling: true
      - model_name: qwen3-235b-a22b-tool
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b-instruct-2507
          api_key: os.environ/FIREWORKS_AI_API_KEY
        model_info:
          supports_function_calling: true
      - model_name: kimi-k2-instruct
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/kimi-k2-instruct
        model_info:
          supports_function_calling: true
      - model_name: qwen3-30b-a3b
        litellm_params:
          model: fireworks_ai/accounts/fireworks/models/qwen3-30b-a3b
        model_info:
          supports_function_calling: true
            
      - model_name: claude-opus-4
        litellm_params:
          model: anthropic/claude-opus-4-20250514
        model_info:
          supports_function_calling: true
      - model_name: claude-sonnet-4
        litellm_params:
          model: anthropic/claude-sonnet-4-20250514
        model_info:
          supports_function_calling: true
          
      - model_name: o4-mini
        litellm_params:
          model: openai/o4-mini
          drop_params: true
        model_info:
          supports_function_calling: true
      - model_name: o4-mini-deep-research
        litellm_params:
          model: openai/o4-mini-deep-research
      - model_name: gpt-4.1
        litellm_params:
          model: openai/gpt-4.1
          drop_params: true
        model_info:
          supports_function_calling: true
      - model_name: gpt-4.1-mini
        litellm_params:
          model: openai/gpt-4.1-mini
          drop_params: true
        model_info:
          supports_function_calling: true
      - model_name: text-embedding-3-small
        litellm_params:
          model: openai/text-embedding-3-small

      - model_name: dall-e-3
        litellm_params:
          model: openai/dall-e-3
        model_info:
          mode: image_generation
      - model_name: whisper-1
        litellm_params:
          model: openai/whisper-1
        model_info:
          mode: audio_transcription
      - model_name: gpt-4o-mini-audio
        litellm_params:
          model: openai/gpt-4o-mini-audio-preview-2024-12-17
        model_info:
          mode: audio_transcription
      - model_name: gpt-4o-transcribe
        litellm_params:
          model: openai/gpt-4o-transcribe
        model_info:
          mode: audio_transcription
      - model_name: gpt-4o-mini-tts
        litellm_params:
          model: openai/gpt-4o-mini-tts
        model_info:
          mode: audio_speech

      - model_name: gemini-2.5-flash
        litellm_params:
          model: gemini/gemini-2.5-flash
          drop_params: true
        model_info:
          supports_function_calling: true
      - model_name: gemini-2.5-pro
        litellm_params:
          model: gemini/gemini-2.5-pro
          drop_params: true
        model_info:
          supports_function_calling: true
      - model_name: gemini-2.5-flash-lite
        litellm_params:
          model: gemini/models/gemini-2.5-flash-lite
          drop_params: true
        model_info:
          supports_function_calling: true