name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add Repos from Charts Automatically
        run: |
          repos=$(find charts -name 'Chart.yaml' -exec yq e '.dependencies[].repository' {} \; | sort -u)
          for repo in $repos; do
            name=$(basename "$repo" | tr -cd '[:alnum:]-')
            echo "Adding repo: $name -> $repo"
            helm repo add "$name" "$repo"
          done
          helm repo update

      - name: Build chart dependencies
        run: |
          for dir in charts/*; do
            if [ -f "$dir/Chart.yaml" ]; then
              echo "Building dependencies for $dir"
              helm dependency build "$dir"
            fi
          done

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
